apiVersion: v1
kind: Service
metadata:
  name: ssltest
  labels:
    app: ssltest
spec:
  ports:
    - port: 443 
      targetPort: 443 
      name: ssltest 
  selector:
    app: ssltest
  type: LoadBalancer
